<!DOCTYPE html><html lang="en"><head><script async src="https://www.googletagmanager.com/gtag/js?id=UA-114897551-4"></script><script>window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'UA-114897551-4');
</script><script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5ac2443d1fff98001395ab6c&amp;product=sticky-share-buttons" async="async"></script><title>#9.3 Exception Handling | Checked Exception | Finally block | Coder Coacher - Coaching Coders</title><meta content="#9.3 Exception Handling | Checked Exception | Finally block - All technical stuff in one place" name="description"><meta name="keywords" content="education, coding, programming, technology, nodejs, mongodb, software, computer science, engineering, teaching, coaching, coder, learning, java, kotlin, machine learning, AI, ML, tech talks, angular, javascript, js, typescript"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" href="/css/font.css"><link rel="stylesheet" href="/css/bootstrap.css"><link rel="stylesheet" href="/css/style.css"><link rel="stylesheet" href="/css/coder-coacher.css"></head><body><div class="container-fluid"><h1 class="site-title"><a href="/">Coder Coacher</a></h1><hr><h4 class="site-subtitle text-right">Coaching Coders</h4></div><div id="amzn-assoc-ad-99d6751e-2392-4004-ad16-73aa8385d9d0"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=99d6751e-2392-4004-ad16-73aa8385d9d0"></script><div class="post__breadcrumb"><div class="container"><ol class="breadcrumb"><li><a href="/">Coder Coacher</a></li><li><a href="/Telusko-Learnings/">Telusko Learnings</a></li><li class="active">â¤µ</li></ol></div></div><h2 class="post__title"><b>#9.3 Exception Handling | Checked Exception | Finally block</b></h2><h5 class="post__date">2018-03-15</h5><div class="container"><div class="video-responsive"><iframe width="560" height="315" src="https://www.youtube.com/embed/gvfmkKRL-GU" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div><div class="post__text">Oh
now once we know about bufferedreader
let's talk about checked exception not
exactly it means if you focus on this
bufferedreader and we have also returned
throws exception what will happen if I
remove that so if you remove that it
says unhandled exception type ru
exception now what exactly it is it says
that this line business Bob BR dot
readline might give you an exception now
what at whatever exception let's say you
are asking for this string value and
then I user is not providing the proper
input but that's an exception right so
whenever you asking for the data from
the preferred eater
due to some user input it will not work
in that scenario it will throw the
exception right and your company knows
about this your company knows that is
this may throw an exception so that's
why it is your compiler asking you to
either use so it is asking you to handle
the exception now there are two ways of
finding the exception we have seen that
one is try catch and second is throws
exception it is compulsory here so if
you if you don't do that if you run this
code it will give you compile time at
all ok so you can see it is it is giving
you an error which is a compile time I
don't know why it is forcing you is
because when we when we have written the
code 4/0 it went that was an exception
right but your compiler was not forcing
us to do that it's because as we have
seen in theory you exceptionally do any
two parts one is checked and unchecked
so when your compiler knows about it
that is checked exception and we our
compiler don't prompt you about the
exception that is uncheck exception now
since it if you go here it says
unhandled exception type IO exception
now since IO exception is not a part of
runtime exception
so only runtime exception subclasses are
unchecked remaining all the exceptions
are checked exception ok so it is
completely for you to handle the
exception so either you can handle the
exception by using try catch or we can
say throws exception and that's what
whenever you is before you do it which
is always good to handle the exception
either with the help of try catch or
with the help of closed exception so
that's how we use bufferedreader and the
exception now what happens is when you
talk about checked exception or way
talk about resources so when you talk
about checked except it is compulsory
for us to handle the exceptions right
now sometime what happens is if I don't
do this if I don't use those exception I
have to use try-catch right so what I
will do now is I will I will declare
this object here and later on I will
create the object of it just here I will
say initially it will be null and then
I'm assigning the value now we have to
use try-catch now where do we use Frank
yet so we'll simply say try here and
we'll say catch exception he and let's
handle the exception here even we can
print the message here would say let's
print itself and the problem is I want
to expand the scope of N and usually it
will be 0 and then somewhere here it
will get its value from the user and you
know that's it that's how let's run this
code now let's see if it is working 78
yeah we got the output what happens is
this BR dot readline I mean this before
Twitter here B R is a resource
now what everybody source so when we
talk about any classes which which comes
with with the help of IO they are
resources which means after using the
resources you have to close it because
if you don't close that miss it is
occupying your memory so once you have
done with this after after this once we
got the input will say BR dot clothes
duties are responsible to close the
bufferedreader and if you're on this
code you can see it is still working if
you try to do something with VR after
this it will not work so it is always
better once you done with your job you
have you should be closing the resources
now the problem is if you get exception
on this line once you've got exception
on that line it will not close the
resource right because you've got an
exception
it will dietician to catch block it will
not close the close the resources so it
is always better to close the resource
it resources in finally block and the
most important use of ia block itself is
to close the resource so you should
always close your resource inside of on
a block ok and just to handle that when
you use those exception here because
you're close itself is throwing an
exception again we can use try catch
there
but it will take lots of code I will use
those exception here it is our
responsibility to close the resources so
create a resource and try/catch handle a
source in cache block and close the
resources in finally go that's how it
should work and if you run this code and
if I give some improper input you can
see me quite an exception this is this
is how it this is how it works right so
that's how you should handle the check
the exception and that's how you should
both use bufferedreader and that's how
you know you should close the resources</div></div><div class="container-fluid bottom-ad"><div id="amzn-assoc-ad-6a809dda-347a-4187-8a86-91faf94575da"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=6a809dda-347a-4187-8a86-91faf94575da"></script></div><div class="text-center">We are a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for us to earn fees by linking to Amazon.com and affiliated sites.</div><script>(function(w, d){
    var b = d.getElementsByTagName('body')[0];
    var s = d.createElement("script"); s.async = true;
    var v = !("IntersectionObserver" in w) ? "8.6.0" : "10.4.2";
    s.src = "https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/" + v + "/lazyload.min.js";
    w.lazyLoadOptions = {};
    b.appendChild(s);
}(window, document));</script></body></html>