<!DOCTYPE html><html lang="en"><head><script async src="https://www.googletagmanager.com/gtag/js?id=UA-114897551-4"></script><script>window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'UA-114897551-4');
</script><script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5ac2443d1fff98001395ab6c&amp;product=sticky-share-buttons" async="async"></script><title>Julia Tutorial - 10. Exception Handling | Coder Coacher - Coaching Coders</title><meta content="Julia Tutorial - 10. Exception Handling - All technical stuff in one place" name="description"><meta name="keywords" content="education, coding, programming, technology, nodejs, mongodb, software, computer science, engineering, teaching, coaching, coder, learning, java, kotlin, machine learning, AI, ML, tech talks, angular, javascript, js, typescript"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" href="/css/font.css"><link rel="stylesheet" href="/css/bootstrap.css"><link rel="stylesheet" href="/css/style.css"><link rel="stylesheet" href="/css/coder-coacher.css"></head><body><div class="container-fluid"><h1 class="site-title"><a href="/">Coder Coacher</a></h1><hr><h4 class="site-subtitle text-right">Coaching Coders</h4></div><div id="amzn-assoc-ad-99d6751e-2392-4004-ad16-73aa8385d9d0"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=99d6751e-2392-4004-ad16-73aa8385d9d0"></script><div class="post__breadcrumb"><div class="container"><ol class="breadcrumb"><li><a href="/">Coder Coacher</a></li><li><a href="/codebasics/">codebasics</a></li><li class="active">â¤µ</li></ol></div></div><h2 class="post__title"><b>Julia Tutorial - 10. Exception Handling</b></h2><h5 class="post__date">2016-04-03</h5><div class="container"><div class="video-responsive"><iframe width="560" height="315" src="https://www.youtube.com/embed/Bar-EdLLV60" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div><div class="post__text">hello everybody let's talk about
exceptions in July programming language
today exceptions are errors detected at
the time of program execution for
example if you try to concatenate string
with a number using plus operator it
will give you this error this is a load
error exception another one is you are
trying to find out the square root of a
negative number and you know that's not
defined so it will give you this domain
error so this is one of the exceptions
so if you go to Julia Lang dot org
website it has a list of all these
exceptions ok so we just looked at
domain error the problem with this
exceptions is that if you are running
your code and if this exception have
happens it will terminate the execution
of the code so sometimes this might be
disastrous what you want to do instead
is whenever exception of course you want
to handle it and gracefully take like a
d2 you know
Bessie you are driving on a road and you
find an accident
you don't terminate driving right you
take a d2 so exception handling is short
of like taking a d2 and finding an
alternate path in your program execution
so here I'm going to show you how you
can use try-catch to handle this at the
square root exception but that you can
write dry
oops I could alter enter by mistake you
are catch so the code that you suspect
might throw an exception you have to
enclose that into this tie catch block
and here in catch you will write a code
that you want to execute upon exception
across so this is short of like a you
are taking a d2 and this is n so due to
this what will happen is your program
will not terminate it will continue
execution even beyond this point okay so
if I execute this it will say exception
occurred okay now here what I did is I
hinder all kind of exceptions into this
generic block sometimes you may want to
know the type of exception and for that
you can specify your exception object
here
so when you say catch why your exception
is stored in this wire object and you
can print that here so if I get altered
it says domain error so the type of
exception that occurred was a domain
error okay
now sometimes you don't know what kind
of exception will happen so you want to
make a check on it and what I'm going to
do here is I will through two kind of
exception so here I have an array and
what i'm doing here is finding the
square root of second element of this
array okay now possible exception that
may happen here is domain error if any
of these elements is less than minus one
if this is minus one then it will result
into a domain error but let's say if I
do something like index array out of
bound then it will omit this error
bounce error like so if you want to do a
specific check on type of exception you
can use is a function we can say if is a
your exception object domain if the type
of exception that is thrown is domain
error then you can just say domain error
domain as is the type of exception is
bounce error okay okay so so now the
same bounce error based on this type
check if I do do and try to find square
root of -1 it will go through this one
so now it hit this one previously it was
hitting this line so this this is how
you can check the type of exception and
based on the time you can do necessary
handling I am just using println right
now but it but in the real world code
you will have you will have a real code
return to handle the type of exception
okay now sometimes you may want to throw
your own exception you talk probably
don't want to use this system generated
exception in that case you can use a
throw statement so here
let's see if I have this kind of code
I'm just throwing the XML straight away
but but you might have some custom
function return' or custom logic where
certain conditions cannot be handled in
which you will throw exception so for
this you will use a true statement and
in the bracket you can specify what type
of exception you want to throw so here
I'm using Dominator again we looked at a
julia website and we have all these
exceptions you can throw any of these or
you can have generic exception object as
well again when I execute this it is
saying domain error okay so that is a
sweet like short and sweet introduction
on exception thanks for watching</div></div><div class="container-fluid bottom-ad"><div id="amzn-assoc-ad-6a809dda-347a-4187-8a86-91faf94575da"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=6a809dda-347a-4187-8a86-91faf94575da"></script></div><div class="text-center">We are a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for us to earn fees by linking to Amazon.com and affiliated sites.</div><script>(function(w, d){
    var b = d.getElementsByTagName('body')[0];
    var s = d.createElement("script"); s.async = true;
    var v = !("IntersectionObserver" in w) ? "8.6.0" : "10.4.2";
    s.src = "https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/" + v + "/lazyload.min.js";
    w.lazyLoadOptions = {};
    b.appendChild(s);
}(window, document));</script></body></html>