<!DOCTYPE html><html lang="en"><head><script async src="https://www.googletagmanager.com/gtag/js?id=UA-114897551-4"></script><script>window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'UA-114897551-4');
</script><script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5ac2443d1fff98001395ab6c&amp;product=sticky-share-buttons" async="async"></script><title>Exceptions with ROB Quiz Solution - Georgia Tech - HPCA: Part 3 | Coder Coacher - Coaching Coders</title><meta content="Exceptions with ROB Quiz Solution - Georgia Tech - HPCA: Part 3 - All technical stuff in one place" name="description"><meta name="keywords" content="education, coding, programming, technology, nodejs, mongodb, software, computer science, engineering, teaching, coaching, coder, learning, java, kotlin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" href="/css/font.css"><link rel="stylesheet" href="/css/bootstrap.css"><link rel="stylesheet" href="/css/style.css"><link rel="stylesheet" href="/css/coder-coacher.css"></head><body><div class="container-fluid"><h1 class="site-title"><a href="/">Coder Coacher</a></h1><hr><h4 class="site-subtitle text-right">Coaching Coders</h4></div><div id="amzn-assoc-ad-99d6751e-2392-4004-ad16-73aa8385d9d0"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=99d6751e-2392-4004-ad16-73aa8385d9d0"></script><div class="post__breadcrumb"><div class="container"><ol class="breadcrumb"><li><a href="/">Coder Coacher</a></li><li><a href="/Udacity/">Udacity</a></li><li class="active">â¤µ</li></ol></div></div><h2 class="post__title"><b>Exceptions with ROB Quiz Solution - Georgia Tech - HPCA: Part 3</b></h2><h5 class="post__date">2015-02-23</h5><div class="container"><div class="video-responsive"><iframe width="560" height="315" src="https://www.youtube.com/embed/u9gTAAMi5wc" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div><div class="post__text">so let's look at our exceptions with
aerobic quiz solution at the point where
this divide has an exception this is
what we had when we go to the exception
handler for this divide what should be
happening is that the instructions
before it has finished and the
instructions after it have not finished
as far as the programmer is concerned so
what we need to really do because
programming really sees only what has
committed here is the fact that this is
done and this is done needs to be undone
so basically this instruction is flushed
from the pipeline it behaves as if it
was not executed at all this instruction
and this instruction as well so pretty
much what we do is when we have an
exception such as divide by 0 the
correct state of the processor should be
right before this instruction if we were
doing these instructions one at a time
so what we do is we roll back the
execution of all these instructions how
do we do that well we have already
committed this instruction before it has
to stay committed we cannot uncommit
instructions this instruction has been
executed and this one has been done what
we do is we wait for them to commit so
what's going to happen is this
instruction will eventually commit once
it's done executing and then this one
also ready done so it can very quickly
commit afterwards now we reach the point
where the divide carries this exception
condition into the commit with it so
when we try to commit the divide we
realize we cannot do that and that's the
point at which we stop committing flush
everything that follows the divide from
the pipeline so these instructions now
become unexecuted meaning we haven't
even fetched them as far as the program
is concerned and this is the point at
which we jump to the exception handler
so pretty much at the point where we
call any exception handler what you have
is some instructions have committed some
of them haven't been even fetched they
have been actually fetched but we have
discarded them so they behave like they
haven't been fetched and that's the
point
where the control is transferred to the
exception handler instead of this way so
it acts very much like a branch
misprediction except that it it happens
on an exception</div></div><div class="container-fluid bottom-ad"><div id="amzn-assoc-ad-6a809dda-347a-4187-8a86-91faf94575da"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=6a809dda-347a-4187-8a86-91faf94575da"></script></div><div class="text-center">We are a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for us to earn fees by linking to Amazon.com and affiliated sites.</div><script>(function(w, d){
    var b = d.getElementsByTagName('body')[0];
    var s = d.createElement("script"); s.async = true;
    var v = !("IntersectionObserver" in w) ? "8.6.0" : "10.4.2";
    s.src = "https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/" + v + "/lazyload.min.js";
    w.lazyLoadOptions = {};
    b.appendChild(s);
}(window, document));</script></body></html>