<!DOCTYPE html><html lang="en"><head><script async src="https://www.googletagmanager.com/gtag/js?id=UA-114897551-4"></script><script>window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'UA-114897551-4');
</script><script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5ac2443d1fff98001395ab6c&amp;product=sticky-share-buttons" async="async"></script><title>Trying Again - Intro to Computer Science | Coder Coacher - Coaching Coders</title><meta content="Trying Again - Intro to Computer Science - All technical stuff in one place" name="description"><meta name="keywords" content="education, coding, programming, technology, nodejs, mongodb, software, computer science, engineering, teaching, coaching, coder, learning, java, kotlin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" href="/css/font.css"><link rel="stylesheet" href="/css/bootstrap.css"><link rel="stylesheet" href="/css/style.css"><link rel="stylesheet" href="/css/coder-coacher.css"></head><body><div class="container-fluid"><h1 class="site-title"><a href="/">Coder Coacher</a></h1><hr><h4 class="site-subtitle text-right">Coaching Coders</h4></div><div id="amzn-assoc-ad-99d6751e-2392-4004-ad16-73aa8385d9d0"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=99d6751e-2392-4004-ad16-73aa8385d9d0"></script><div class="post__breadcrumb"><div class="container"><ol class="breadcrumb"><li><a href="/">Coder Coacher</a></li><li><a href="/Udacity/">Udacity</a></li><li class="active">â¤µ</li></ol></div></div><h2 class="post__title"><b>Trying Again - Intro to Computer Science</b></h2><h5 class="post__date">2015-02-23</h5><div class="container"><div class="video-responsive"><iframe width="560" height="315" src="https://www.youtube.com/embed/Hb7_ygaj0h8" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div><div class="post__text">so let's look at an example of how we
use try so here we've created a try
block and everything inside this block
will execute and it will execute
normally until there's an exception
raised if there's an exception raised it
will jump to look for an exception
handler and in this case we have an
exception handler for the i/o error
exception so if that's raised it'll be
handled here and then after the try
block finishes we'll continue with it
print note that there's a few things in
this code you might not have seen yet
you should be starting to get
comfortable with that if you're confused
by things like for example this line
here you can probably figure out on your
own what it does either looking through
the documentation or trying it in the
interpreter so let's try running this
code and I'm trying it in a directory
that does not have any trippy file and
we can see what happens when this line
executed the exception was thrown it was
an i/o error exception that got bound to
the variable E and then we print out
there we can see error reading file the
message that came with exception and
then after that it doesn't return here
execution continues following the try
block at the print statement one of the
things exceptions do is make it much
harder to follow the flow of execution
of a program code can jump all around
it's different from procedures which do
make code jump around but when we call a
procedure normally and it returns
normally we know it's always going to
come back to the same point with
exceptions anywhere in here can jump to
another place so now I've created a file
called trippy but I've made it
unreadable don't worry if you don't
understand these commands these are just
ways to create a file and make it
unreadable and now i'm going to try
again and we see we still got the i/o
error exception but the message is
different now we got a permission
failure because we don't have permission
to read the file that exists there let's
make the file readable and try n now we
get something different so now the open
succeeded we got to the next line the
next line does a red line that succeeded
we read in the line what a trip and then
we got to the next line which tries to
convert that line to a number using the
int constructor that through a value
error exception and so when an exception
is raised inside a try block
it jumps to the exception handlers the
i/o error exception handler doesn't
match value error so it doesn't handle
it there's no exception handler that
does handle the value error so that
exception gets raised to the next level
in this case causing the program to
crash and that's why instead of ever
getting to continuing we got this error
when we ran the program</div></div><div class="container-fluid bottom-ad"><div id="amzn-assoc-ad-6a809dda-347a-4187-8a86-91faf94575da"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=6a809dda-347a-4187-8a86-91faf94575da"></script></div><div class="text-center">We are a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for us to earn fees by linking to Amazon.com and affiliated sites.</div><script>(function(w, d){
    var b = d.getElementsByTagName('body')[0];
    var s = d.createElement("script"); s.async = true;
    var v = !("IntersectionObserver" in w) ? "8.6.0" : "10.4.2";
    s.src = "https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/" + v + "/lazyload.min.js";
    w.lazyLoadOptions = {};
    b.appendChild(s);
}(window, document));</script></body></html>