<!DOCTYPE html><html lang="en"><head><script async src="https://www.googletagmanager.com/gtag/js?id=UA-114897551-4"></script><script>window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'UA-114897551-4');
</script><script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5ac2443d1fff98001395ab6c&amp;product=sticky-share-buttons" async="async"></script><title>CppCon 2017: Jody Hagins “Throwing Exceptions for Fun and Profit” | Coder Coacher - Coaching Coders</title><meta content="CppCon 2017: Jody Hagins “Throwing Exceptions for Fun and Profit” - All technical stuff in one place" name="description"><meta name="keywords" content="education, coding, programming, technology, nodejs, mongodb, software, computer science, engineering, teaching, coaching, coder, learning, java, kotlin, machine learning, AI, ML, tech talks, angular, javascript, js, typescript"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" href="/css/font.css"><link rel="stylesheet" href="/css/bootstrap.css"><link rel="stylesheet" href="/css/style.css"><link rel="stylesheet" href="/css/coder-coacher.css"></head><body><div class="container-fluid"><h1 class="site-title"><a href="/">Coder Coacher</a></h1><hr><h4 class="site-subtitle text-right">Coaching Coders</h4></div><div id="amzn-assoc-ad-99d6751e-2392-4004-ad16-73aa8385d9d0"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=99d6751e-2392-4004-ad16-73aa8385d9d0"></script><div class="post__breadcrumb"><div class="container"><ol class="breadcrumb"><li><a href="/">Coder Coacher</a></li><li><a href="/CppCon/">CppCon</a></li><li class="active">⤵</li></ol></div></div><h2 class="post__title"><b>CppCon 2017: Jody Hagins “Throwing Exceptions for Fun and Profit”</b></h2><h5 class="post__date">2017-10-31</h5><div class="container"><div class="video-responsive"><iframe width="560" height="315" src="https://www.youtube.com/embed/uRZZ8_d4nGM" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div><div class="post__text">Alright, there's my title,
because naming things are hard.
So we do use exceptions in our code base
even though we are very
concerned about performance.
I'll avoid the holy war about exceptions,
but the other night at
dinner with some folks
we were talking about it
and we were discussing why
we use it and some things
that we did in our performance
testing originally.
I thought it may be interesting to share
some this stuff out.
I'm gonna make that bigger
'cause that looks like it's too small.
There we go.
This is basically, on the left part it say
function that we just made up,
but it's just a function
that uses a return code,
You're just gonna return a value from it.
As normal status stuff right,
it's just a stupid function
but it shows us what we want.
And this is the code that it generates.
So this is kind of what we want to get
if we can create our
throwing of the exception.
A lot of times you talk
about catching of exceptions.
We can get it to look similar to this
then that's kind of where we want to be.
So let's see what we can do.
In this case,
we have,
we've replaced the returns with throws.
And you can see here's the function
and it has grown tremendously.
There's lots and lots of extra code there.
Most of that is actually
because when you call throw,
it's going to inline all
that code to actually
create the exception and throw it.
So let's try and get rid of that.
So what we can do is,
we can have a function.
We can have a run-time error
and a logic error function.
It's an extern function
that will actually,
that you run so it doesn't get inline.
Now we can see that the
code is very similar
to what we had before.
It's almost exactly the same,
give or take.
So what this is gonna
do, it'll at least save
some I-cache for us.
But I don't like having these
run-time and logic errors
basically having a function
for every type of exception,
so what can we do, let's try templates,
because that's what we always try
anytime we have a problem.
(audience laughing)
So we write a template to,
whoops did I not go to the right one?
There we go.
So we have a template that
raises the exception for us
and so we call raise, and what we do is
we give it a type and it
does perfect forwarding
so we can give it all this arguments
and they're perfect for
the arguments at exception.
But we end up with all
that same code again.
This basically looks just like the throw.
So what can we do?
If we use the attributes, we can then
make this function be no inline code
and tell it that it's never gonna return,
and the code gets generated.
Looks just like the original stuff,
except for there's your
functions for your templates,
but the code for the actual
function is that right there.
You can and to see the difference
between the piece on the left,
I can't really explode this up,
but the piece on the left is the function
that uses a status code and
does a return of the status.
The function on the right
is the one that throws the exceptions
and they're pretty much side by side,
you can see where they go.
The ideas that we don't wanna
pay for what we don't use,
and that is both in execution instructions
of what we're gonna execute
in the performance time
but also we don't wanna have
a bunch of code sitting around
that we're never gonna use
except in exceptional situations.
There's a couple other
things that we can do here.
We can have a,
we can take our source location
and eventually the standard
may or may not include this
in some future version,
but for now what we can do
is we can record our source location
every time we throw an exception.
We can call arrays, we
have to use a macro.
But in this case, if we
call raise with the macro,
we can include the line function and file.
It would be set for every
time we call function,
every time we throw an exception,
and so then all we have
to do is query and call.
Current exception source location,
every time we get an exception
and we'll actually get
the file function and line
from where the exception originated.
Which may or may not be helpful for you.
One last thing, if I
have time, I think I do.
Oops, wrong one.
Alright, so this here, down at the bottom,
if you see, this is a loop.
If you're gonna be catching exceptions,
it's not a good idea.
So just let your program crash,
not really.
But there is a small
expense we're catching.
So if you have a loop that's gonna be
running things over and
over and over again,
if you have your catch
inside of the tight loop
you're gonna end up generating
this code over here.
So what I do is I have
an external for loop
and then a try, and then inside of that,
my for loop that does this stuff,
so that the catch is
outside of that for loop,
it'll throw at exception, it'll come out,
and then if I still need a loop backup,
I'll come back again,
but then I only have that code path once.
There we go.
Go make money throwing exceptions.
(audience applauding)</div></div><div class="container-fluid bottom-ad"><div id="amzn-assoc-ad-6a809dda-347a-4187-8a86-91faf94575da"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=6a809dda-347a-4187-8a86-91faf94575da"></script></div><div class="text-center">We are a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for us to earn fees by linking to Amazon.com and affiliated sites.</div><script>(function(w, d){
    var b = d.getElementsByTagName('body')[0];
    var s = d.createElement("script"); s.async = true;
    var v = !("IntersectionObserver" in w) ? "8.6.0" : "10.4.2";
    s.src = "https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/" + v + "/lazyload.min.js";
    w.lazyLoadOptions = {};
    b.appendChild(s);
}(window, document));</script></body></html>